# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotasks',
            name='playbook_text',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
