# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tasks', '0002_autotasks_playbook_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotasks',
            name='playbook_text',
        ),
        migrations.AddField(
            model_name='autotasks',
            name='status',
            field=models.CharField(choices=[('Y', '\u5df2\u6267\u884c'), ('N', '\u672a\u6267\u884c')], default='N', max_length=1, verbose_name='\u6267\u884c\u72b6\u6001'),
        ),
    ]
